name: Pipeline Básica

on:
  push:
    branches: ["main"]   
  pull_request:
    branches: ["main"]   

jobs:
  testar:
    runs-on: ubuntu-latest   

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Exibir mensagem de teste
        run: echo "Pipeline funcionando com sucesso!"
